"""add updated_at to review_jobs

Revision ID: 91801a79cc5b
Revises: 001_review_jobs
Create Date: 2026-07-23 20:59:59.560184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91801a79cc5b'
down_revision: Union[str, None] = '001_review_jobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_jobs', 'updated_at')
    # ### end Alembic commands ###
