"""Add DiscoveredModel table

Revision ID: f9f8368f2ff3
Revises: 7798fbb499b6
Create Date: 2026-08-07 20:48:48.547608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9f8368f2ff3'
down_revision: Union[str, None] = '7798fbb499b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_slug', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('raw_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discovered_models'))
    )
    op.create_index(op.f('ix_discovered_models_id'), 'discovered_models', ['id'], unique=False)
    op.create_index(op.f('ix_discovered_models_is_free'), 'discovered_models', ['is_free'], unique=False)
    op.create_index(op.f('ix_discovered_models_provider_slug'), 'discovered_models', ['provider_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discovered_models_provider_slug'), table_name='discovered_models')
    op.drop_index(op.f('ix_discovered_models_is_free'), table_name='discovered_models')
    op.drop_index(op.f('ix_discovered_models_id'), table_name='discovered_models')
    op.drop_table('discovered_models')
    # ### end Alembic commands ###
